Events allow unenrollment
aditikilledar/burnout-proj3 pull request #37
Opened 2023-11-18 21:08 UTC by shashank-madan

Made entire event card clickable, 
Can enroll as well as unenroll from events in events page.

2023-11-18 21:53 UTC, srina1h requested changes

2023-11-18 21:53 UTC, srina1h commented on frontend/src/components/Events.js
> +                                    </CardActions> */}
Can you remove this comment?

2023-11-19 00:17 UTC, shashank-madan commented on frontend/src/components/Events.js
> +                                    </CardActions> */}
Done

2023-11-19 17:27 UTC, aditikilledar approved these changes

2023-11-19 17:49 UTC, srina1h approved these changes

2023-11-19 17:49 UTC, merged